  // netlify.toml
[build]
  command = "npm run build"
  publish = "dist" 

[build.environment]
  VITE_API_KEY = "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"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200